### ISSUE TITLE
Summer of Bitcoin Project Proposal: Work on developing bdk-python

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoindevkit/bdk-ffi#102]
## Description
The Bitcoindevkit is using language bindings to offer packages and libraries in different languages. [bdk-python](https://github.com/thunderbiscuit/bdk-python) is fairly new (December 2021), but shows great promise. We are looking for someone knowledgeable with Python to help develop the package into a more mature [package on PyPI](https://pypi.org/project/bdkpython/).

The student would be working with the team to further the goals of the bitcoindevkit and make meaningful progress towards the expected outcomes defined in the next section.

## Expected Outcomes
Develop the test suite, enable automatic deployment using GitHub Actions, writing of small example applications leveraging the library, blog posts, and documentation. This project is for someone interested in bringing the library to a more mature state on PyPI, and working alongside the bdk-kotlin and bdk-swift libraries to ensure consistent APIs and code coverage.

## Resources
The bitcoindevkit project currently maintains four language bindings libraries: [bdk-jvm](https://github.com/bitcoindevkit/bdk-kotlin), [bdk-android](https://github.com/bitcoindevkit/bdk-kotlin), [bdk-swift](https://github.com/bitcoindevkit/bdk-swift), and [bdk-python](https://github.com/thunderbiscuit/bdk-python). There is good working knowledge of how those bindings work within the team.

## Skills Required
Good working knowledge of Python.

## Difficulty
Medium.

**Comment by monalisha31** [comment]
Hello @thunderbiscuit  , I would like to prepare a proposal for this project. Is there any competency test, that i need to complete?

**Comment by sayskar500** [comment]
@thunderbiscuit have trying to reach out to you for some time regarding some issues to be discussed regarding the task.

**Comment by thunderbiscuit** [comment]
Folks I'll be removing `bdk-python` as a Summer of Bitcoin project. After looking into it over the past week I don't think it's ready and mature enough to be part of the mentorship and guidance type of structure that is expected and required of a good Summer of Bitcoin project.

This is not to say we don't want you to keep contributing! Just that it will not be part of the Summer of Bitcoin project proposals anymore.
