### ISSUE TITLE
Add TxBuilder control coin selection methods

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk-ffi#131]
Add methods to TxBuilder to allow users to control coin selection.

Note this issue requires Wallet.list_unspent() to be implemented first to get some OutPoints for testing.

See https://docs.rs/bdk/latest/bdk/wallet/tx_builder/struct.TxBuilder.html for docs on what the functions do. 

```udl

interface TxBuilder {
  ... 
  TxBuilder add_unspendable(OutPoint unspendable);
  TxBuilder add_utxo(OutPoint outpoint);
  TxBuilder add_utxos(sequence<OutPoint>);
  TxBuilder do_not_spend_change();
  TxBuilder manually_selected_only();
  TxBuilder only_spend_change();
  TxBuilder unspendable(sequence<OutPoint>);
}

```

**Comment by zoedberg** [comment]
Really interested in this feature!

I was wondering if manually selecting UTXOs and setting `manually_selected_only` will be enough in order to set an absolute fee (that will be equal to the total input amount minus the total output amount) or if the `fee_absolute` method will be necessary in order to do that. Could you clarify this, please?

**Comment by notmandatory** [comment]
I believe that even if you use `add_utxo` and `manually_selected_only` you will also need to use `fee_absolute`  to get an absolute fee since the coin selection will only use the specified utxos it needs to pay the outputs and some given fee or fee rate. You can see the rust docs here: https://docs.rs/bdk/latest/bdk/wallet/tx_builder/struct.TxBuilder.html#method.add_utxo

And if you want to test it out you can use the `bdk-cli` tool, see the options with `bdk-cli wallet -d <descriptor> help create_tx`, the `bdk-ffi` behavior will be the same as `bdk-cli`.

**Comment by zoedberg** [comment]
I've implemented all the requested methods plus the `fee_absolute` one. Since this depends on the [list unspent PR](https://github.com/bitcoindevkit/bdk-ffi/pull/158) I think I should wait for that to be merged before opening a PR for this but feel free to assign me this issue in the meanwhile :)

**Comment by notmandatory** [comment]
You're also welcome to open a draft PR for some early feedback, but fine to wait until #158 is merged too.
