### ISSUE TITLE
Add tests for TxBuilder API

### ISSUE THREAD

**Issue by artfuldev** [bitcoindevkit/bdk-ffi#141]
We need to add tests for the FFI layer of TxBuilder API as we're dealing with some local state. We need a few test wallets which are funded in order to test. cc @notmandatory

**Comment by notmandatory** [comment]
I'm moving this back to the backlog, it should be unblocked once #148 is merged.

**Comment by artfuldev** [comment]
Is this back on?

**Comment by thunderbiscuit** [comment]
If I understand correctly this issue can now be closed. Feel free to reopen if I misunderstood.
