### ISSUE TITLE
Enable Transaction member access

### ISSUE THREAD

**Issue by CerberusVT** [bitcoindevkit/bdk-ffi#142]
Hi!

The Transaction object it's not very useful at this moment.
When you get it you cannot access to the details or confirmed and unconfirmed data classes.

**Comment by thunderbiscuit** [comment]
Maybe I don't understand what you mean exactly so let me know if this doesn't solve your issue, but this is how you might access the details on a given transaction in Kotlin:

```kotlin
val txHistory = Wallet.listTransactions()
val myFirstTransaction = txHistory[0]
val details = when (tx) {
    is Transaction.Confirmed -> tx.details
    is Transaction.Unconfirmed -> tx.details
}
println(tx.fees, tx.received, tx.sent, tx.txid)
```

The data class looks like this:
```kotlin
data class TransactionDetails (
    var fees: ULong?, 
    var received: ULong, 
    var sent: ULong, 
    var txid: String 
)
```

**Comment by CerberusVT** [comment]
> Maybe I don't understand what you mean exactly so let me know if this doesn't solve your issue, but this is how you might access the details on a given transaction in Kotlin:
> 
> ```kotlin
> val txHistory = Wallet.listTransactions()
> val myFirstTransaction = txHistory[0]
> val details = when (myFirstTransaction) {
>     is Transaction.Confirmed -> tx.details
>     is Transaction.Unconfirmed -> tx.details
> }
> println(details.fees, details.received, details.sent, details.txid)
> ```
> 
> The data class looks like this:
> 
> ```kotlin
> data class TransactionDetails (
>     var fees: ULong?, 
>     var received: ULong, 
>     var sent: ULong, 
>     var txid: String 
> )
> ```

Thanks for the info! 

I close this issue
