### ISSUE TITLE
Make `Wallet::sign` return, and `Wallet::broadcast` consume, a `SignedBitcoinTransaction`

### ISSUE THREAD

**Issue by artfuldev** [bitcoindevkit/bdk-ffi#15]
We can use `FinalizedBitcoinTransaction` if that's better terminology.

**Comment by artfuldev** [comment]
@notmandatory opened this for discussion. I think we can have a better API by making it impossible to broadcast an unsigned transaction at compile-time.

**Comment by notmandatory** [comment]
Sounds like something that could be done in a `bdk` PR, is that what you're thinking?

**Comment by thunderbiscuit** [comment]
This doesn't apply anymore (or rather is sort of solved?), as the `Wallet.sign()` and the `Blockchain.broadcast()` now consume and return a PSBT respectively.
