### ISSUE TITLE
Add functions to get current block height and hash

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk-ffi#151]
Once getting a block hash is supported in `bdk` then should add ability to get current block height and block hash at a given height to the `Blockchain` interface. These functions are needed to help support wallets that also use LDK, See https://github.com/bitcoindevkit/bdk-swift/issues/10.

Depends on:
  - [x] https://github.com/bitcoindevkit/bdk/issues/603

**Comment by ConorOkus** [comment]
Hi @notmandatory @thunderbiscuit any idea when this might be available in the rest of the bindings?

**Comment by thunderbiscuit** [comment]
I think `get_block_hash` was merged in `0.21.0`, so it's now ready to be brought in for the next release.
