### ISSUE TITLE
Bugs in bdk-ffi 0.6.0

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoindevkit/bdk-ffi#155]
Just opening this so others can find it.

`0.6.0` came with a sqlite-related bug in bdk `0.18.0`. Issue bitcoindevkit/bdk#591 and fix in PR bitcoindevkit/bdk#605.

This made the balance increase on each sync of the wallet and the `wallet.getTransactions` error out. Fix will be provided in bdk `0.19.0`, which we will bring into bdk-ffi `0.6.1`.

**Comment by notmandatory** [comment]
Good idea opening an issue. One small change is I think we'll need to bump the `bdk-ffi` version to `0.7.0` when we go to bdk `0.19.0` since it will big a big `bdk` change that also includes new (experimental) P2TR support.

**Comment by thunderbiscuit** [comment]
Oh that makes sense 🚀.

**Comment by i5hi** [comment]
Just bumped into this issue. Thanks for mentioning. Waiting for 0.19.0 :)
