### ISSUE TITLE
Expose xpub in ExtendeKeyInfo

### ISSUE THREAD

**Issue by allisonmoyer** [bitcoindevkit/bdk-ffi#156]
Related to issue #138 and pull request #139 - our team wants the ability to use xpubs in wallet descriptors when creating a wallet and later sign transactions with the xprv, so we need a reference to the xpub in the ExtendedKeyInfo 

cc @notmandatory

**Comment by notmandatory** [comment]
Do you need to also sign arbitrary messages as in #139? Or just be able to make a watch only descriptor with xpubs and also sign PSBTs with an xprv based version of the same descriptor? If the later I think #154 will provide what you need.

**Comment by allisonmoyer** [comment]
Ah, I didn't see #154, yeah that's exactly what we're looking for at this point, thanks. Any rough idea of timeline for #154 completion?

**Comment by notmandatory** [comment]
We just merged @dhruv-1001's PR #154 which should do what you want. It will be in the next releases of `bdk-ffi`, `bdk-kotlin`, and `bdk-swift`.
