### ISSUE TITLE
Remove generated bindings code and dylib binary from source control

### ISSUE THREAD

**Issue by artfuldev** [bitcoindevkit/bdk-ffi#16]
![image](https://user-images.githubusercontent.com/3091087/137599525-36d4f3d5-1351-4bf7-b5a2-6e4edc1f877a.png)
This kotlin % would just be very small (test/demo source) if we didn't have generated bindings here - and since generated bindings are just outputs, it might be a good idea to isolate them from source control.

We would still need to figure out how to test stuff. For the demo application and tests, I just use `./gradlew` right now and run everything from the terminal. There might be a way to run these tests / code from scripts/clis without having to setup a complete kotlin project setup committed to source control

**Comment by notmandatory** [comment]
When we setup CI testing we can use a localhost `regtest` network instance of `bitcoind` and `electrsd` nodes, this is how the `bdk` CI works. See also:

https://crates.io/crates/bitcoind
https://crates.io/crates/electrsd

**Comment by artfuldev** [comment]
Yeah I guess the testing part is clear.

**Comment by artfuldev** [comment]
But we still have generated code in our source control for now - including the dylib. It gets a diff every time too 😅
