### ISSUE TITLE
Create a type safe descriptor builder

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk-ffi#165]
As discussed in the team chat with kirillzhukov, the `bdk` lib uses rust macros to provide a type safe way to construct valid descriptors. Since the macro approach won't work for `bdk-ffi` language bindings we should try to build a simple library, possibly as a new repo, that uses simple structs and enums to accomplish something similar to the `bdk::descriptor::dsl` module.

**Comment by thunderbiscuit** [comment]
Related to #98.

**Comment by notmandatory** [comment]
Yes it's related to the static templates, they both should result in some `Descriptor` structure that can be used when constructing a `Wallet`.

**Comment by notmandatory** [comment]
Had a related discussion on Discord `bdk-users` today and think a simple descriptor template api could look like below. These represent simple single key descriptors according to [BIP44],[BIP49],[BIP84], and [BIP86]. 

There's no BIP yet for multisig templates, but we could create a simple one that takes a given key threshold and array of keys, would also need to a `DescriptorKey` enum.

```udl
[Enum]
interface DescriptorKey {
  Public(DescriptorPublicKey key);
  Secret(DescriptorSecretKey key);
};

interface Descriptor {
  [Throws=Error]
  constructor(string descriptor);

  [Name=new_bip44]
  constructor(DescriptorSecretKey secret_key, KeychainKind keychain , u32 account);

  [Name=new_bip44_public]
  constructor(DescriptorPublicKey public_key, string fingerprint, KeychainKind keychain , u32 account);

  [Name=new_bip49]
  constructor(DescriptorSecretKey secret_key, KeychainKind keychain , u32 account);

  [Name=new_bip49_public]
  constructor(DescriptorPublicKey public_key, string fingerprint, KeychainKind keychain , u32 account);
  
  [Name=new_bip84]
  constructor(DescriptorSecretKey secret_key, KeychainKind keychain , u32 account);
  
  [Name=new_bip84_public]
  constructor(DescriptorPublicKey public_key, string fingerprint, KeychainKind keychain , u32 account);
  
  [Name=new_bip86]
  constructor(DescriptorSecretKey secret_key, KeychainKind keychain , u32 account);
  
  [Name=new_bip86_public]
  constructor(DescriptorPublicKey public_key, string fingerprint, KeychainKind keychain , u32 account);

  [Name=new_multisig]
  constructor(sequence<DescriptorKey> keys, u32 threshold);

  string to_string();
};
```

**Comment by notmandatory** [comment]
Related link with the types of descriptors other wallets use: https://github.com/nvk/walletsrecovery.org

**Comment by BitcoinZavior** [comment]
This looks great 👍 
Apart from the standard templates, we can have a custom descriptor option as well, so that a path and script type can be specified and the descriptor will be created for it.
- This will take care of existing wallets created with non standard path.
- It will also allow users to create wallets based on instructions from existing wallets which may not specify or inform the users of a descriptor nor a standard template but provide a path to use.
- API to create a single XPub descriptor or a single key descriptor has been requested many times by users and having a custom descriptor option will take care of the request.

**Comment by notmandatory** [comment]
> This looks great 👍 Apart from the standard templates, we can have a custom descriptor option as well, so that a path and script type can be specified and the descriptor will be created for it.

That's a great idea! But let's do it in a separate PR once we have the standard templates working ok? I'll think I'll move the multisig into it's own PR too since it might require it's own API discussion.

**Comment by BitcoinZavior** [comment]
> That's a great idea! But let's do it in a separate PR once we have the standard templates working ok? I'll think I'll move the multisig into it's own PR too since it might require more API discussion also.

Sounds good 👍

**Comment by thunderbiscuit** [comment]
@notmandatory mind if I take this on?

**Comment by thunderbiscuit** [comment]
Now that I'm looking at the templates from BDK I see they only build for account 0 (if you want/need a different account you must build the descriptor manually).

**Comment by notmandatory** [comment]
> Now that I'm looking at the templates from BDK I see they only build for account 0 (if you want/need a different account you must build the descriptor manually).

Good point, I agree for the initial api let's stick with just what the BDK templates give us, so account 0 only. Before we support different accounts I want to get that supported in the`bdk` templates.

**Comment by danielnordh** [comment]
Only here to say that I support this effort of adding 'ready to go' descriptor types.
It was one of the hurdles for me in getting started, I had to go ask in discord to figure it out.

In my own Swift code I only got to describe two so far:

```swift
public enum DescriptorType {
    case singleKey_wpkh84 // Native Segwit
    case singleKey_tr86 // Taproot
}
```

You have more detailed knowledge about a wider range of types so I don't have much to add, other than please name them in an approachable and descriptive way. (Or at least add comments in the code).

**Comment by notmandatory** [comment]
This is a good point about the naming. In BDK the templates are named by the bipxx + public added if they are for creating public key watch only descriptors, so that's what I am proposing for bdk-ffi. But we we'll certainly need to add docs for anyone who's unfamiliar with the bips.
