### ISSUE TITLE
Expose the set_recipients() API from the TxBuilder

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoindevkit/bdk-ffi#168]
This will allow us to provide a list of recipients instead of calling the `.add_recipient()` method multiple times on the `TxBuilder`.

**Comment by notmandatory** [comment]
@waterst0ne has started looking into this one

**Comment by notmandatory** [comment]
Also need to change the `finish()` method to use this:

https://docs.rs/bdk/latest/bdk/wallet/tx_builder/struct.TxBuilder.html#method.set_recipients

**Comment by thunderbiscuit** [comment]
Awesome work!
