### ISSUE TITLE
Move functionality from `build.sh` to `build.rs` and use feature flags to indicate which bindings to generate

### ISSUE THREAD

**Issue by artfuldev** [bitcoindevkit/bdk-ffi#17]

**Comment by thunderbiscuit** [comment]
I'm building part of that functionality in #122.

**Comment by notmandatory** [comment]
As we discussed on our last call I think the best approach for now is to create a `uniffi-bindgen` generate tool as @thunderbiscuit has started with #122. And then to convert the existing `build.sh` scripts in `bdk-kotlin` and `bdk-swift` to the preferred Kotlin or Swift build tools such as in https://github.com/bitcoindevkit/bdk-kotlin/pull/37.

**Comment by artfuldev** [comment]
Isn't this effectively closed now? @notmandatory

**Comment by notmandatory** [comment]
Fixed by https://github.com/bitcoindevkit/bdk-ffi/pull/126
