### ISSUE TITLE
Naming differences between bindings and Rust API

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoindevkit/bdk-ffi#181]
I believe there are two naming differences between the bindings API and the Rust API on the TxBuilder:
1. Our `TxBuilder` uses `get_transactions()` instead of the bdk `list_transactions()` method
2. Our `TxBuilder` uses `get_network()` instead of the bdk `network()` method

Fixing these would create breaking changes but I think we should continue to strive for name parity with the upstream library if we can.

**Comment by notmandatory** [comment]
Good idea! I agree.
