### ISSUE TITLE
Currently rust-bip39 only supports bip39 word counts divisible by 6 

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk-ffi#226]
**Describe the bug**  

This issue is a reminder so we don't forget to fix this.

The `WordCount` enum allows users to pick word counts that aren't divisible by 6, but `bdk` is using the `rust-bip39` crate which only allows word counts that are divisible by 6. See:

https://docs.rs/bip39/1.0.1/src/bip39/lib.rs.html#245-261

**To Reproduce**  

Create a `Mnemonic` with `WordCount` of 15 words and an error is returned.

**Expected behavior**  

When using the `WordCount` enum all the variants should be valid. 

**Build environment**  
 - BDK tag/commit: v0.11.0 
 - OS+version: any
 - Rust/Cargo version: 1.60
 - Rust/Cargo target:  any

**Additional context**  

The  next version of `rust-bip39` should fix this issue with https://github.com/rust-bitcoin/rust-bip39/pull/18.

This is the PR where bdk switched to using `rust-bip39` bitcoindevkit/bdk#462

See also [BIP-39](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki).

**Comment by thunderbiscuit** [comment]
This is resolved by https://github.com/bitcoindevkit/bdk/pull/875.
