### ISSUE TITLE
Rename repository to something more intuitive

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoindevkit/bdk-ffi#232]
As discussed in a dev call this sounds like a great idea. The only thing is that it might break links all over the place and people who are currently aware of the project might loose bookmarks and such. If we rename it we should think about publicly announcing it. But I think it makes a lot of sense to do it prior to the `1.0` release, and even more so because the specific libraries are/will be in this repository, so this repo is now not only the FFI layer but also all of the bindings.

**Comment by notmandatory** [comment]
I think the name bdk-bindings or bdk-language-bindings sound good. Want to hear what the rest of the team thinks.

**Comment by thunderbiscuit** [comment]
After discussions on various dev calls I think the name we have will stick. Closing this for now.
