### ISSUE TITLE
Hiding LogProgress from electrum users

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoindevkit/bdk-ffi#239]
If I remember correctly the `LogProgress` callback is not being used by Electrum servers, and since it's one of the most prominent ways to use the libraries on mobile, I'm wondering how we can hide that away from users of the library (it's always been a bit weird for users, as we've seen in the Discord mobile channel and just from even my own experience).

Is there a way for us to maybe provide a default implementation defined directly in the bdk.rs file? Something that users could override if they need but don't have to code in otherwise?

**Comment by notmandatory** [comment]
This needs to be fixed in bdk, see bitcoindevkit/bdk#798.
