### ISSUE TITLE
Document best approach for working with Java apps

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk-ffi#244]
Reported by SeverinAlexB on discord. See also:

https://github.com/SeverinAlexB/bdk-java-ulong-bug

**Comment by thunderbiscuit** [comment]
This issue has been further investigated, and I want to provide links for people stumbling on this. The core problem is that unsigned types are inline classes, and their names get [mangled](https://kotlinlang.org/docs/inline-classes.html#mangling). The primary fix is to write small Kotlin wrapper classes, but I will expand on different approaches in a separate issue.

Links:
1. [Kotlin YouTrack Issue](https://youtrack.jetbrains.com/issue/KT-57161#focus=Comments-27-6950327.0-0)
2. [Mangling](https://kotlinlang.org/docs/inline-classes.html#mangling)
