### ISSUE TITLE
Add support for iOS 14.0

### ISSUE THREAD

**Issue by allisonmoyer** [bitcoindevkit/bdk-ffi#254]
The current minimum target of bdk-swfit is iOS 15.0, which limits consumers to using iOS 15.0 as their minimum as well. My team is using 14.0 as our minimum, so we'd need bdk-swift to support 14.0 as well

cc @notmandatory

**Comment by thunderbiscuit** [comment]
I'm not sure if this is coming from the uniffi library or some configuration we've set up. @reez any idea where this is defined? If it's not anywhere on our end I'm happy to open an issue on the uniffi repo and ask where this is defined and if indeed iOS 15.0 is really as low as they go.

**Comment by reez** [comment]
I believe its defined strictly by us in the [Package.swift](https://github.com/bitcoindevkit/bdk-ffi/blob/master/bdk-swift/Package.swift) file, so we can bump iOS/macOS versions up+down there:

```
    platforms: [
        .macOS(.v12),
        .iOS(.v15)
    ],
```

**Comment by thunderbiscuit** [comment]
@reez I wonder if we can just try it locally and make sure that changing that one line will support 14.0. I don't see anything on the uniffi repository that says they have a minimum iOS supported version. 

Can you test this locally easily? If it works it's an easy win. Sorry it took me so long to get to this Allison.

**Comment by reez** [comment]
@allisonmoyer is your min iOS14 still or is the min iOS15+ now? I'm assuming that you don't need iOS14 support anymore (but if you do let me know and I'll work on this for ya'll)-

**Comment by allisonmoyer** [comment]
@reez yeah we're iOS 15+ now, so no longer needed 🙂

**Comment by reez** [comment]
Makes sense, thanks!
