### ISSUE TITLE
Add support for Cocoapods distribution

### ISSUE THREAD

**Issue by allisonmoyer** [bitcoindevkit/bdk-ffi#255]
bdk-swift is currently distributed via Swift Package Manager. For developers using Cocoapods (like my team), we'd like to be able to consume bdk-swift via Cocoapods.

I've started attempting to add support, but running into issues https://github.com/allisonmoyer/bdk-swift/pull/1

cc @notmandatory

**Comment by notmandatory** [comment]
Closing since @allisonmoyer team is now using SPM. :-)
