### ISSUE TITLE
Building with bdk-swift for "Any Mac" target fails

### ISSUE THREAD

**Issue by wolfmcnally** [bitcoindevkit/bdk-ffi#256]
I am developing on an M1 Mac.

My app has a dependency on bdk-swift. When I build it for the simulator, or "My Mac (designed with iPad)" it builds fine:

![image](https://user-images.githubusercontent.com/676176/171039843-c4ce63f8-e51e-483e-ac3e-6b0184c02d33.png)
No issues.

![image](https://user-images.githubusercontent.com/676176/171039504-b9a3c4c4-ae5e-4a6d-8c68-5a3e66d8639f.png)
No issues.

When I build it for "Any iOS Device (arm64)" it also works:

![image](https://user-images.githubusercontent.com/676176/171040212-a5d14af3-4d55-481d-a22e-6f46464f6e56.png)
No issues.

But when I build it for "My Mac (Rosetta)" or "My Mac (Mac Catalyst)" the build fails:

![image](https://user-images.githubusercontent.com/676176/171039515-2e871aa7-5145-4a84-825d-0a56d721dade.png)
![image](https://user-images.githubusercontent.com/676176/171039523-8764df51-ab92-4190-b601-7e57a5a43187.png)

![image](https://user-images.githubusercontent.com/676176/171039529-b0487075-2b79-496e-89f0-2d13452bedbe.png)
![image](https://user-images.githubusercontent.com/676176/171039534-43ad63c7-566b-4179-992d-c25b9592700f.png)

Of course it also fails when building for "Any Mac":
![image](https://user-images.githubusercontent.com/676176/171040372-31167cc7-cd15-4067-b46e-7b5fa7d47c26.png)
![image](https://user-images.githubusercontent.com/676176/171040397-dfb709fa-2ca2-44f2-95c9-b0ce2e4377af.png)

Expected behavior:

bdk-swift as a dependency should work for all the above targets.

**Comment by notmandatory** [comment]
Will re-open if @wolfmcnally is still having this issue.
