### ISSUE TITLE
Expose input and output addresses in TransactionDetails / Transaction

### ISSUE THREAD

**Issue by danielnordh** [bitcoindevkit/bdk-ffi#267]
Any wallet app will need to show the to and from addresses in the transaction history.
This should be included in the TransactionDetails, either separately or exposing the Transaction available in BDK.

See these closed issues for reference:
bitcoindevkit/bdk-swift#27 
https://github.com/bitcoindevkit/bdk-ffi/issues/179

**Comment by thunderbiscuit** [comment]
With #307, the `TransactionDetails` type will have the full Transaction as a field. This will allow users to scan for the list of inputs and the list of outputs, which contain their Script. All we need is the utility method on the script type to transform those into addresses and we solve this issue. I will add this method to the PR as it's already a big refactor around transactions and transaction details.

**Comment by thunderbiscuit** [comment]
Completed! I'm very happy we got this one in.
