### ISSUE TITLE
Expose fingerprint for `DescriptorPublicKey`

### ISSUE THREAD

**Issue by allisonmoyer** [bitcoindevkit/bdk-ffi#268]
**Describe the Enhancement**  
We're designing our data storage and plan to store private keys separately from public keys, but we want a way to look up a corresponding private key for a public key so would like to do so via their `fingerprint`. It would be nice to have a `fingerprint` property on `DescriptorPublicKey` in order to do so.

**Comment by notmandatory** [comment]
Per [BIP-0032](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki) it looks like fingerprints are only specified for xkeys not single keys, and you will have to be able to deal with possible fingerprint collisions, is that OK? The way `bdk` (via `rust-miniscript`) internally deals with looking up secret keys from public keys is with a hash map keyed by the full public key.

**Comment by allisonmoyer** [comment]
@notmandatory ahh I see, thanks for the context! Using the full public key makes sense, we'll do that 👍
