### ISSUE TITLE
Stale doc on Wallet getBalance & Blockchain broadcast

### ISSUE THREAD

**Issue by shobitb** [bitcoindevkit/bdk-ffi#284]
The `Wallet.getBalance` documentation says that it returns a `ULong` balance ([bdk-android 0.25.0 docs](https://bitcoindevkit.org/android/bdk-android/org.bitcoindevkit/-wallet/index.html#627873659%2FFunctions%2F769193423)) ([bdk-jvm 0.25.0 docs](https://bitcoindevkit.org/jvm/bdk-jvm/org.bitcoindevkit/-wallet/index.html#627873659%2FFunctions%2F769193423))

https://github.com/bitcoindevkit/bdk-ffi/blob/bada9b82e08dd97842facc391fec5f43b6591142/api-docs/kotlin/src/main/kotlin/org/bitcoindevkit/bdk.kt#L371

but getBalance actually returns a type `Balance`

https://github.com/bitcoindevkit/bdk/blob/0b768d6f0b9ea4edc49f52044e829a4d8fa8debf/src/wallet/mod.rs#L469-L474

Similarly, `Blockchain.broadcast` documentation says that it returns a `String` when in fact it returns nothing.
https://github.com/bitcoindevkit/bdk-ffi/blob/master/bdk-ffi/src/bdk.udl#L164

**Comment by thunderbiscuit** [comment]
Good catch. Would you be able to open the PR to fix?

**Comment by shobitb** [comment]
Sure! How does this look? https://github.com/bitcoindevkit/bdk-ffi/pull/285

**Comment by shobitb** [comment]
OK, after some edits and git amends and squashes I think I'm finally ready! https://github.com/bitcoindevkit/bdk-ffi/pull/285/commits

Thanks!
