### ISSUE TITLE
Feature request: add fee estimator bindings

### ISSUE THREAD

**Issue by kirillzh** [bitcoindevkit/bdk-ffi#287]
We are looking into various options for implementing fee estimation functionality on Android and iOS. [BDK Fee Estimator](https://docs.rs/bdk/latest/bdk/blockchain/trait.Blockchain.html#tymethod.estimate_fee) looks like something we could use but it's not currently exposed via bindings.

cc @valerio86, @allisonmoyer

**Comment by notmandatory** [comment]
I agree this seems like an important missing API for any mobile wallet. The rust API is only a pass-through to what ever blockchain client you've configured, but still seems useful to make that uniform API available.

**Comment by shobitb** [comment]
I, too, needed this function in an app I'm building.  So I made an attempt to add the binding myself.

Please review.  I'm not a Rust expert, so any comments on my Rust (particularly the return types, etc) would be greatly appreciated!

Thank you!
