### ISSUE TITLE
Add check for missing environment variables in Android plugin

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoindevkit/bdk-ffi#295]
We could throw an error with a useful message when either of `ANDROID_SDK_ROOT` or `ANDROID_NDK_ROOT` is an empty string.

**Comment by reez** [comment]
Is this for when in a local Android dev environment with something like Android Studio somehow either `ANDROID_SDK_ROOT` or `ANDROID_NDK_ROOT` environment variables are unset or empty (either by it not happening automatically or manually)? Noob Android dev question from me.

**Comment by thunderbiscuit** [comment]
Yes exactly. The plugin assumes you have at least the ANDROID_SDK_ROOT variable defined, but this is actually brittle because it doesn't let you know why the build fails when it does if you didn't have it set. Fixing now.

**Comment by reez** [comment]
> Yes exactly. The plugin assumes you have at least the ANDROID_SDK_ROOT variable defined, but this is actually brittle because it doesn't let you know why the build fails when it does if you didn't have it set.

cool, thanks for that explanation!
