### ISSUE TITLE
Expose entire PartiallySignedTransaction struct

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoindevkit/bdk-ffi#311]
The [PartiallySignedTransaciton](https://docs.rs/bitcoin/0.29.2/bitcoin/util/psbt/struct.PartiallySignedTransaction.html) type is a big boy. Lots of new inner types.

But overall I think this is the type of thing people need for complete introspection. I'm opening this issue to discuss whether we should expose the entirety of the type including all inner types or go a slightly different way. I'll post an example UDL file to propose the definition of the new API.

**Comment by dhruv-1001** [comment]
To include all the inner types, we'll have to bring all the types to the `bdk-ffi` and these types would not be used for anything else.
What do you think about including a method to `PartiallySignedTransaction` something like `return_tree` that return an enum after processing the `PartiallySignedTransaction` to include everything inside of that PartiallySignedTransaction. 
This `enum` would follow this JSON pattern :
```rust
enum JsonValue {
    None,
    Number(f64),
    String(String),
    Array(Vec<JsonValue>),
    Object(std::collections::HashMap<String, JsonValue>),
}
```
@thunderbiscuit does this make sense? Is there any ffi limitation that I might have overlooked.

**Comment by thunderbiscuit** [comment]
Hey thanks for starting to think about this issue!

I'm not sure I understand the added value of the json approach you have in mind. What does it offer that is better than exposing the type completely? One of our goals for the bindings is to mimic as close as we can the Rust side of things, and so if we are to depart from that, I really want to make sure it's for good reasons and the tradeoffs are worth it.

**Comment by dhruv-1001** [comment]
The idea was to having not need to include all the Inner types in `bdk.udl` file, and therefore making it less cluttered.

**Comment by BitcoinZavior** [comment]
@notmandatory This will help with some of the requests. This will expose all the inputs as well as outputs. Hence detailed transaction data can be extracted.
