### ISSUE TITLE
bdk_cd24_Blockchain_get_height returns wrong block height

### ISSUE THREAD

**Issue by geigerzaehler242** [bitcoindevkit/bdk-ffi#313]
**Describe the bug**  
bdk_cd24_Blockchain_get_height returns the block height for "tbtc" and not "btc"

**To Reproduce**  
//swift code
let blockChainUrl = "ssl://blockstream.info/api"
let electrum = ElectrumConfig(url: "ssl://electrum.blockstream.info:60002", socks5: nil, retry: 5, timeout: nil, stopGap: 10, validateDomain: true)
            
let blockchainConfig = BlockchainConfig.electrum(config: electrum)
let blockchain = try Blockchain(config: blockchainConfig)
let tempBlockHeight = try blockchain.getHeight()

//sdk
public func `getHeight`() throws -> UInt32 {
        return try FfiConverterUInt32.lift(
            try
    rustCallWithError(FfiConverterTypeBdkError.self) {
    bdk_cd24_Blockchain_get_height(self.pointer, $0

**Expected behavior**  
the block height it currently returns is in the 2,420,437 range which is the block height for tbtc and not btc

the true btc block height currently would be 777,048

**Build environment**  
 [BitcoinDevKit.swift and Package.swift](https://github.com/bitcoindevkit/bdk-swift) for release 0.26.0 

**Additional context**  
i think you included a "t" by accident somewhere in the code

**Comment by thunderbiscuit** [comment]
In this case you are using a testnet electrum server, which is why it's returning the latest testnet block height!

For mainnet, your blockchain config should have the following url:
```swift
let electrum = ElectrumConfig(
    url: "ssl://electrum.blockstream.info:50002", 
    socks5: nil, 
    retry: 5, 
    timeout: nil, 
    stopGap: 10, 
    validateDomain: true
)
```

Let me know if that works for you!
```

**Comment by geigerzaehler242** [comment]
yes thanks, that was the problem. i am getting the correct block height now.

**Comment by thunderbiscuit** [comment]
No problem. Feel free to come say hi on the Discord server and let us know what you're building!

I'm also always looking for Swift contributors to this repo: https://github.com/thunderbiscuit/bitcoindevkit-scripts if that's something you're interested in.
