### ISSUE TITLE
Create Swift iOS Demo Wallet

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk-ffi#318]
**Description**

The Bitcoin Development Kit (BDK) is a library that allows developers to seamlessly build cross-platform bitcoin wallets without worrying about bitcoin internals. The [`bdk-ffi`] project provides language bindings that allow a BDK based wallet to be built on mobile platforms such as Android and iOS. To help new developers get started it's useful to have a template project for the platform they are developing for. There is already a template Android wallet project called [`devkit-wallet`] and a very basic iOS example called [`BdkSwiftSample`]. The goal of this project is to build a swift + iOS demo wallet project using the BDK swift bindings that has comparable  functionality to the Android `devkit-wallet` project. The `BdkSwiftSample` project can be used as a starting point, the new project should follow iOS app development best practices. 

  

[`bdk-ffi`]: https://github.org/bitcoindevkit/bdk-ffi
[`devkit-wallet`]: https://github.com/thunderbiscuit/devkit-wallet
[`BdkSwiftSample`]: https://github.com/futurepaul/BdkSwiftSample

**Expected Outcomes**  
   

- Create Xcode iOS wallet project 
- Document process to build and test wallet
- Create basic automated testing

Required wallet features are:

- Build app using the SwiftUI framework
- Create new wallet and display BIP39 recovery words
- Receive bitcoin
- Send bitcoin
- Sync wallet using Electrum
- Retrieve and display transaction history
- Restore wallet using BIP39 recovery words

**Resources**  
  
  
  
  

- Read the bdk-ffi API by reading the [Android docs].
- Understand the best practices for developing an iOS app, see ["Develop apps for iOS"]
- Have used a bitcoin mobile wallet such as [Muun]
- [Build a bitcoin wallet with SwiftUI](https://bdgwallet.notion.site/bdgwallet/Build-a-bitcoin-wallet-with-SwiftUI-a9b09fef617143948babf0641086c353#7c1c3459bfb9451580b42840eecec391)
- [Build a bitcoin wallet with SwiftUI Part 2](https://bdgwallet.notion.site/bdgwallet/Build-a-bitcoin-wallet-with-SwiftUI-Part-2-UI-Styling-905e4db372ca48a4ad9d926449bcbc78)

[Android docs]: https://bitcoindevkit.org/android/
["Develop apps for iOS"]: https://developer.apple.com/tutorials/app-dev-training
[Muun]: https://muun.com/

**Skills Required**  
  
  
  
  

- Hands on experience with git and GitHub
- Know how to set up your git/GitHub signing key and sign git commits, see ["Managing commit signature verification"](https://docs.github.com/en/authentication/managing-commit-signature-verification)
- Experience using the Swift programming language
- Experience using Xcode
- Bonus: created any sort of iOS app with Swift

**Mentor(s)**  
@notmandatory
@reez

**Difficulty**  
Medium

**Competency Test**  

- Create a new git repository on GitHub
- Create a new Xcode iOS project (SwiftUI framework) in the your new repo, add the files with a signed commit
- Modify the README.md file with a signed commit
- Extra: Modify your iOS app to do something more than the basic template behavior

**Comment by reez** [comment]
This repo can be found here: https://github.com/reez/BDKSwiftExampleWallet

Would you like me to add a PR to https://github.com/bitcoindevkit/bitcoindevkit.org to add it here https://bitcoindevkit.org/examples/ ?

**Comment by reez** [comment]
Opened a PR for this on bitcoindevkit.org: https://github.com/bitcoindevkit/bitcoindevkit.org/pull/158

**Comment by reez** [comment]
I think we can close this now, but I won't close it myself I'll leave that up to @notmandatory / @thunderbiscuit

**Comment by notmandatory** [comment]
At some point I would like to have our example android and swift mobile wallets in the bitcoindevkit repo to make them easier to find. @thunderbiscuit and @reez any thoughts we should chat about if/how to do this.

**Comment by reez** [comment]
Definitely, will request to add to the bindings call topic list
