### ISSUE TITLE
Expose SignOptions struct

### ISSUE THREAD

**Issue by damiandizeo** [bitcoindevkit/bdk-ffi#323]
Would be cool be able to set SignOptions like [allow_all_sighashes](https://docs.rs/bdk/latest/bdk/wallet/signer/struct.SignOptions.html#structfield.allow_all_sighashes) when a psbt needs to be signed by the wallet. An use would case be when we need import a psbtBase64 from other wallet that contain a custom sighash

**Comment by notmandatory** [comment]
It's not really a bug, more of a missing feature. But anyway something that needs to be added to the language bindings.
