### ISSUE TITLE
PyPi does not load BDK correctly.

### ISSUE THREAD

**Issue by Rob1Ham** [bitcoindevkit/bdk-ffi#339]
**Describe the bug**  
While compiling from source it works appropriately, but when downloading from PyPi it does not work.

**To Reproduce**  
Here is the logs from my terminal:

```
 rob@macbook workbench % pip install bdkpython==0.27.1
ERROR: Could not find a version that satisfies the requirement bdkpython==0.27.1 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4)
ERROR: No matching distribution found for bdkpython==0.27.1
 rob@macbook workbench % pip install bdkpython
Collecting bdkpython
  Using cached bdkpython-0.0.4-py3-none-any.whl (10.1 MB)
Installing collected packages: bdkpython
Successfully installed bdkpython-0.0.4
 rob@macbook workbench % python3
Python 3.9.13 (main, Aug 25 2022, 18:29:29) 
[Clang 12.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import bdkpython as bdk
>>> descriptor = bdk.Descriptor("wpkh(tprv8ZgxMBicQKsPcx5nBGsR63Pe8KnRUqmbJNENAfGftF3yuXoMMoVJJcYeUw5eVkm9WBPjWYt6HMWYJNesB5HaNVBaFc1M6dRjWSYnmewUMYy/84h/0h/0h/0/*)", bdk.Network.TESTNET) 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'bdkpython' has no attribute 'Descriptor'
```

Was running on my MacOSXv 13.2.1 with intel chips.

**Comment by notmandatory** [comment]
@thunderbiscuit I'd like to get this figured out for the 0.28 release so tagging it there.  It sounds like somehow the python bindings code is generated correctly but the corresponding rust binary libs aren't being added the the packages.

**Comment by thunderbiscuit** [comment]
If it does work, I'm not sure of the best approach to provide it out of the box. The CI currently builds with the latest possible image for GitHub Actions for macOS, `macos-12`. There might be ways to go around that and make the CI build macOS 13 wheels, but... not sure yet how one would go about doing that. We'd need to dig a bit more.

**Comment by thunderbiscuit** [comment]
I believe this is now resolved with some of the new build processes! If it isn't, feel free to reopen.
