### ISSUE TITLE
Rename non-public inner struct fields as "inner"

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk-ffi#366]
**Describe the enhancement**  

In a few places we need to "wrap" a bdk or rust-bitcoin struct in a bkd-ffi struct and make the original type a non-public "inner" field. We've used different names for these inner fields but should standardize on the name "inner" for consistency and readability. Examples of stucts that need to be changed:

Transaction.internal
Address.address
Script.script
Blockchain.blockchain_mutex
Mnemonic.internal
DerivationPath.derivation_path_mutex
DescriptorPublicKey.descriptor_public_key_mutex
DescriptorSecretKey.descriptor_secret_key_mutex
Input._inner
PartiallySignedTransaction.internal
Wallet.wallet_mutex

**Use case**  

Users won't see this change.

**Additional context**

The name "inner" is common in other libraries like `rust-bitcoin`.

**Comment by tarunsamanta2k20** [comment]
I'd like to look into this.
