### ISSUE TITLE
Enhancement request: Expose allow_shrinking to TxBuilder

### ISSUE THREAD

**Issue by andreasgriffin** [bitcoindevkit/bdk-ffi#375]
**Describe the enhancement**  
The method TxBuilder.[allow_shrinking](https://docs.rs/bdk/latest/bdk/wallet/tx_builder/struct.TxBuilder.html#method.allow_shrinking)  is not yet exposed.  

**Use case**  
This feature is necessary for wallet-ui features like "Send-max".  A possible wallet implementation is: Selecting an outpoint as "send-max" will set the output to the sum of all input amounts (essentially leaving 0 sats for the fee) and with [allow_shrinking](https://docs.rs/bdk/latest/bdk/wallet/tx_builder/struct.TxBuilder.html#method.allow_shrinking)  shrink this outpoint to pay the fees specified in [fee_rate](https://docs.rs/bdk/latest/bdk/wallet/tx_builder/struct.TxBuilder.html#method.fee_rate).

**Comment by andreasgriffin** [comment]
It seems for this method holds:  `methods supported only by bump_fee`

**Comment by thunderbiscuit** [comment]
Hi @andreasgriffin!

Tell me more about the exact user workflow you're trying to achieve; I think you probably are able to do it already (if it's about sending the entirety of a UTXO and using that same UTXO to pay for the fees using a mix of `drain_to`, `add_utxo` and `manually_selected_only`). I'm happy to write a small example for you (unless you mean something else I didn't understand).

For the allow_shrinking method, you're correct it only applies in the context of bumping a transaction using BIP-125. The method is [exposed in the BumpFeeTxBuilder here](https://github.com/bitcoindevkit/bdk-ffi/blob/master/bdk-ffi/src/wallet.rs#L497-L507).

**Comment by andreasgriffin** [comment]
Hi @thunderbiscuit :  Thanks for pointing out `drain_to` in combination with `manually_selected_only` (that's a useful combination).  That works, and I [implemented](https://github.com/andreasgriffin/bitcoin-safe/blob/0a0ada75f5866f480c0b0fc83b7833dd6ccb85dd/bitcoin_safe/wallet.py#L1188) it already :-)

Before I did that manually, by creating a dummy tx first, getting the total fee and then deducting the total fee from the remaining utxo value.

**Comment by thunderbiscuit** [comment]
Sweet! Happy to hear you got your workflow working. Looking forward to seeing/learning more about what you project does!

**Comment by andreasgriffin** [comment]
I'm afraid with https://github.com/bitcoindevkit/bdk-ffi/pull/374 I cannot help either.
