### ISSUE TITLE
wallet sync is scanning 200 addresses

### ISSUE THREAD

**Issue by Czino** [bitcoindevkit/bdk-ffi#385]
**Describe the bug**  
Using bdk-rn, I already raised an issue in their repo: https://github.com/LtbLightning/bdk-rn/issues/44

> When syncing, even after after creating a fresh wallet with a stopGap setting of 5, I am logging 200 requests on my electrum server.
> Changing the stopGap does not have any influence on these 200 requests. I even set it to 500 but still only see 200 requests
> Tested with BlockchainEsploraConfig and BlockchainElectrumConfig
> Tested on Android and iOS

However, after checking multiple times that `stopGap` is being passed correctly, I'd like to escalate the issue one level higher.

**Expected behavior**  
- `stopGap` being respected during scan, if I set 10  I would expect a scan of `20` addresses at most (receiving+change addresses)
- Using default: `stopGap` being `25` by default.

**Build environment**  
 - BDK tag/commit: v0.27.0
 - OS+version: Android, iOS

**Comment by thunderbiscuit** [comment]
I can reproduce using bdk-kotlin. Even with a stopgap of 1 the wallet will sync 100 addresses (given an external descriptor only). 

I will try to reproduce in Rust.

**Comment by thunderbiscuit** [comment]
This is solved with the new syncing in bdk 1.0, and we have no plans to fix the bug for versions `0.X`. Closing this now.
