### ISSUE TITLE
Typescript bindings

### ISSUE THREAD

**Issue by demattosanthony** [bitcoindevkit/bdk-ffi#386]
**Describe the enhancement**  
Would love for typescript bindings to be added

**Use case**  
I want to use this in a browser environment for a wallet PWA I am creating. I am using the LDK typescript bindings for a lightning node and would love to use this instead of bitcoinjs-lib

**Comment by notmandatory** [comment]
We don't currently have any plans to support typescript since there's no planned support in the `uniffi-rs` framework which we rely on. See:  https://github.com/mozilla/uniffi-rs/issues/1361

**Comment by demattosanthony** [comment]
@notmandatory it is possible to compile to wasm and use that in a typescript app?

**Comment by thunderbiscuit** [comment]
You would not compile this to WASM, but you could use the WASM bindings for bdk directly! I have not used them myself, but my understanding is that they are used by a fair number of projects, the most prominent of which is probably Mutiny Wallet. Check out their codebase for ideas on how to leverage the WASM bindings, or open an issue on the Rust bdk repo directly! Cheers.
