### ISSUE TITLE
Look into framework zip file bdkFFI.xcframework in bdk-swift

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoindevkit/bdk-ffi#427]
The file hasn't been updated in 2 years, and I wonder if it should be removed from the repo (the zip file that I think is important is in the artifacts associated with the releases rather than the source code of the repository).

Need to look into this more. Tagging @reez to keep track.

**Comment by notmandatory** [comment]
To add to @reez's description above we use the `bdkFFI.xcframework` directory of files as a template to copy compiled rust binary's into. The `bdkFFI.xcframework` directory in the `bdk-ffi/bdk-swift` project is only used for local testing. In the `bdk-swift` repo the `bdkFFI.xcframework` directory is used to create the final zip that is also never committed but is uploaded to github as part of the Swift Package release process.

**Comment by thunderbiscuit** [comment]
Will add this to the dev call tomorrow. If I understand correctly what you are both saying, it's not needed as part of the (bdk-swift) repo, since the Package.swift file points to the zipped artifact in the releases, and the actual framework committed to the repo never gets used or pulled by any code?

**Comment by notmandatory** [comment]
Yes to be clear we should be able to remove the `bdkFFI.xcframework` directory from the `bdk-swift` repo.
