### ISSUE TITLE
Code Review tooling

### ISSUE THREAD

**Issue by reez** [bitcoindevkit/bdk-ffi#459]
**Describe the enhancement**  
Possibly add [coderabbitai](https://coderabbit.ai/)

[$0](https://coderabbit.ai/#pricing) for open source

I first saw it on an [LDK pull request](https://github.com/lightningdevkit/rust-lightning/pull/2812) and it piqued my interest 

**Use case**  
it is an AI first code reviewer

**Comment by notmandatory** [comment]
I'd like to try it! even if we only end up using the the high level summaries that would be very helpful. And the price is right.

**Comment by notmandatory** [comment]
I turned it on from my account for the `bdk-ffi` repo. Let's see how it goes.

**Comment by reez** [comment]
> I turned it on from my account for the `bdk-ffi` repo. Let's see how it goes.

Nice you're like reading my mind because I wanted to do a quick simple test of it before using it on a bdk repo just to make sure it was working well so I enabled it on Monday to do a [simple PR test](https://github.com/reez/Monday/pull/84) which worked well, and I was gonna see if you were cool turning it on for one of the bdk repos when I caught up with you later this week. Perfect! 

Can you enable it on [BDKSwiftExampleWallet](https://github.com/bitcoindevkit/BDKSwiftExampleWallet) too? I've got a couple smaller PR's I can open up on that repo for some more testing and trying it out. Here's an example of what it looked like for me yesterday to "Request" or "Grant" access to the orgs I'm a part of, I'm assuming those "Requests" for bitcoindevkit will go to you:

<img width="1512" alt="Screenshot 2024-02-27 at 12 26 02 PM" src="https://github.com/bitcoindevkit/bdk-ffi/assets/6657488/412ee9a3-7173-445c-9417-f762cdf2c52a">
