### ISSUE TITLE
Allow language support from external crates

### ISSUE THREAD

**Issue by artfuldev** [bitcoindevkit/bdk-ffi#48]

**Comment by notmandatory** [comment]
There is also a uniffi-rs issues for this here: https://github.com/mozilla/uniffi-rs/issues/299

**Comment by thunderbiscuit** [comment]
I'm trying to clean up our open issues and PRs: if it's ok with you folks I'll close this one.

**Comment by thunderbiscuit** [comment]
This issue should be opened with uniffi-rs if still required. Closing this as it's not in scope for bdk-ffi to fix.
