### ISSUE TITLE
Consider cutting release for bdk-android 0.31.1

### ISSUE THREAD

**Issue by jurvis** [bitcoindevkit/bdk-ffi#505]
**Describe the enhancement**  
👋 I know 0.31.1 was released to fix a warning Xcode 15.3 shows because we don't have Info.plist the xcframework. 

Could we do a similar version bump to make 0.31.1 available on `bdk-android` as well  (even if there are no material changes there) so we don't have to pin different versions which could be confusing? 🙂

Thanks!

**Comment by thunderbiscuit** [comment]
Done! 

[Android](https://central.sonatype.com/artifact/org.bitcoindevkit/bdk-android/0.31.1). 
[Kotlin/JVM](https://central.sonatype.com/artifact/org.bitcoindevkit/bdk-jvm/0.31.1)
