### ISSUE TITLE
Exposing Errors 

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoindevkit/bdk-ffi#509]
It turns out that errors are not easy to move from Rust to the target languages when using uniffi. In short, it looks like one must choose between a range of options, each with pros and cons, and none particularly perfect. This issue is an attempt at quantifying and categorizing these options and the choices we made for the bdk-ffi language bindings.

**Comment by thunderbiscuit** [comment]
## Option 1
One requirement you might have for errors is that their fields be exposed to the bindings. For example, the `TxidParseError` would like to return to the user not only it's variant's name, but the txid that was not parsable:
```rust
#[derive(Debug, thiserror::Error)]
pub enum TxidParseError {
    #[error("invalid txid: {txid}")]
    InvalidTxid { txid: String },
}
```

In the UDL, this shows up as:
```txt
[Error]
interface TxidParseError {
  InvalidTxid(string txid);
};
```

When building bindings code for this however, the resulting exception thrown will not use the message you might expect (the one built by `thiserror`). Instead, a custom `message` field is built which simply prints the names of the fields in the enum and their value:
```kotlin
sealed class TxidParseException: Exception() {
    class InvalidTxid(val txid: String) : TxidParseException() {
        override val message
            get() = "txid=${ `txid` }"
}
```

This means that we cannot customize the message given to the user; the `thiserror` library does not help us, and following this approach, one must choose between a custom error message and the fields one might want to expose. For example, instead of a message like
```txt
invalid HTTP header value: {value}
```
You only send back to the Koltin/Swift user an exception with a field `message`, which would print as
```txt
value=${value}
```

This is inconvenient, and overall doesn't provide the sort of information one might want to convey. We really want to customize our error messages, but we also need to bring in our data! This leads us to option 2.

## Option 2

**Comment by reez** [comment]
This is an awesome breakdown. 1 or 3 definitely are our best bets.

**Comment by thunderbiscuit** [comment]
So it turns out there is a 4th option. If you use a struct as an error type instead of an enum, your struct can implement the Display trait which will populate the `toString()` method in Kotlin and Swift, and also contain the full typed data inside. The [Mozilla test-fixtures have a good example of this](https://github.com/mozilla/uniffi-rs/tree/main/fixtures/error-types).

This is maybe less applicable for us because it means your errors are not variants of an enum and are simply objects by themselves. It turns out you can combine them into an enum if you want I think, but then you loose the nice Display features.

I'm adding this to the post above just to keep all options in one big comment.

**Comment by reez** [comment]
> I prefer option 1 because it give apps access to the error data with which they can construct their own user facing errors, as long as we have good error docs that should be enough context for developers. If we go with option 3 we get the nice english error message strings, but those would need to be parsed somehow to get to the data so would be hard to localize and would be less usable in an app UI.

I just added a comment to our ErrorADR a few mins ago that I think aligns with this general concept you're describing: https://github.com/bitcoindevkit/bdk-ffi/pull/513#discussion_r1620888196 `Libraries return errors and applications decide if and how those errors are formatted and displayed to users.`

**Comment by thunderbiscuit** [comment]
We have solidified our approach to exposing error for now. I don't know that it's perfect but I do think it strikes a good balance. Closing this now.
