### ISSUE TITLE
Support `bdk-jni` APIs used by `padawan-wallet`

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk-ffi#54]
By supporting the existing [`bdk-jni`](https://github.com/bitcoindevkit/bdk-jni) APIs we will be able to support the [`padawan-wallet`](https://github.com/thunderbiscuit/padawan-wallet) project and other projects that are currently using `bdk-jni`.

- [x] Construct/destruct Wallet with db name, network, db path, descriptor, change descriptor
- [x] Construct Wallet with Sled key/value DB 
- [x] Construct Wallet electrum blockchain client
- [x] Get new address from Wallet
- [x] Sync Wallet with blockchain
- [x] Get Wallet balance, in satoshis
- [x] List transactions
- [x] Create a transaction with single recipient
- [x] Sign PSBT with default options
- [x] Broadcast a PSBT
- [x] Generate an extended key
- [x] Restore an extended key
- [x] #60
- [x] #61
- [x] #62

**Comment by artfuldev** [comment]
Everything's done!
