### ISSUE TITLE
Use bdk_electrum upstream

### ISSUE THREAD

**Issue by reez** [bitcoindevkit/bdk-ffi#567]
**Describe the bug**  

Just adding an Issue to track that we will move back to `bdk_electrum` (and not a fork of it) at some point.

Changed in bdk-ffi alpha 13:

```
bdk_electrum = { git = "https://github.com/thunderbiscuit/bdk/", package = "bdk_electrum", branch = "feature/electrum-client-ring-ffi-alpha13", default-features = false, features = ["use-rustls-ring"] }
# bdk_electrum = { version = "0.15.0" }
```

Related PR's for this:
- [bdk](https://github.com/bitcoindevkit/bdk/pull/1491)
- [rust-electrum-client](https://github.com/bitcoindevkit/rust-electrum-client/pull/135)

**Additional context**

**Comment by thunderbiscuit** [comment]
Done!
