### ISSUE TITLE
Fork and update `padawan-wallet` to use `bdk-android`

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk-ffi#58]

**Comment by artfuldev** [comment]
Made changes at https://github.com/artfuldev/padawan-wallet/tree/upgrade-bdk
Just need to update to a deployed/published package

**Comment by artfuldev** [comment]
Currently uses a published package.
Blocked on #64
Will be unblocked via #74

**Comment by artfuldev** [comment]
Completed via https://github.com/thunderbiscuit/padawan-wallet/pull/148
