### ISSUE TITLE
API surface of the `Wallet` type

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoindevkit/bdk-ffi#596]
After taking some time to look at what parts of the `Wallet` API were available/not available/useful for the bindings, many methods stood out. This issue will track them. Note that not all of those are top priority, but most of them we figured would be useful and not too costly to include either in the first version of the 1.0 or in a future feature release (1.1, 1.2, etc.)

- [x] Wallet::peek_address
- [x] Wallet::cancel_tx
- [x] Wallet::next_derivation_index
- [x] Wallet::derivation_of_spk
- [x] Wallet::descriptor_checksum
- [x] Wallet::finalize_psbt
- [x] Wallet::get_utxo
- [x] Wallet::list_unused_addresses
- [x] Wallet::mark_used
- [x] Wallet::next_unused_address
- [x] Wallet::policies
- [x] Wallet::public_descriptor
- [x] Wallet::reveal_addresses_to
- [x] ~Wallet::unbroadcast_transactions~

**Comment by rustaceanrob** [comment]
What I would consider high priority:`finalize_psbt`, `cancel_tx`, `public_descriptor`, `descriptor_checksum`. I can hack at those if others agree they should be included in `1.0`

**Comment by thunderbiscuit** [comment]
The `Wallet::unbroadcast_transactions` method requires exposing the [`TxNode`](https://docs.rs/bdk_chain/0.20.0/bdk_chain/tx_graph/struct.TxNode.html) type, which is a bit more than I want to do at the moment for a method no one has asked directly. 

I'd be great to define the exact use case for this (I think its about creating unbroadcast transactions so as to lock the UTXOs for transaction builder, and eventually to take stock maybe of those tx we've created and maybe want to cancel using `cancel_tx()`? Need to dig a bit more.

**Comment by thunderbiscuit** [comment]
With the merge of #626 and #625 this list will be complete.
