### ISSUE TITLE
Publish Kotlin, Android and JVM, artifacts to MavenCentral

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk-ffi#64]
https://sergiomartinrubio.com/articles/how-to-publish-a-java-library-to-maven-central/

https://weibeld.net/java/publish-to-maven-central.html

https://github.com/rwinch/gradle-publish-ossrh-sample

https://docs.gradle.org/current/userguide/signing_plugin.html

**Comment by artfuldev** [comment]
Fixed in #73 and #74
