### ISSUE TITLE
Provide static library as part of bdk-jvm

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoindevkit/bdk-ffi#78]
I know the jars don't ship with the `libbdkffi.dylib` in them by default. Would a FAT jar be a solution for this or can they just be included with some configuration setting we need to turn on?

Other temporary solution would be to make them available as artifacts for download as part of the release page on GitHub.

**Comment by artfuldev** [comment]
We do have the required binary, it's just currently only supporting the only one platform (linux). Linking the libs is kind of a painful process that we're trying to avoid for consumers of our packages, so we will be bundling most target libraries into the same package. We have an issue #76 tracking the same.
