### ISSUE TITLE
Implement basic spending policy APIs

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk-ffi#80]
**Description**

Add or update APIs in `bdk-ffi` to support basic spending policy features. Also test the new APIs by updating `bdk-kotlin` or `bdk-swift` to use the new and updated APIs. See ["Spending Policy Demo"] for `bdk-cli` based example usage.

APIs include:

1. Giving a wallet, return Policy structure (as Dictionary?) for "external" and "internal" descriptors.
1. When creating a transaction PSBT, specify the "external policy" to use

**Expected Outcomes**  
* Update `bdk.udl` and `lib.rs` with functions and structs as needed
* Update `bdk-kotlin` or `bdk-swift` and add tests to cover new spending policy functionality 

**Resources**
* [BDK Website](https://bitcoindevkit.org)
* [BDK github repo](https://github.com/bitcoindevkit/bdk)
* [BDK Discord](https://discord.gg/dstn4dQ)
* [uniffi-rs](https://mozilla.github.io/uniffi-rs/)

**Skills Required**  
* Experience with git. [Guide](https://git-scm.com/book/en/v2)
* Basic familiarity with rust. [First seven chapters of the book](https://doc.rust-lang.org/book/)
* Basic familiarity with Kotlin or Swift
* Familiarity with bitcoin descriptors and [miniscript](https://bitcoin.sipa.be/miniscript/) policies

**Mentor(s)**  

@artfuldev @notmandatory 

**Difficulty**  

Medium

**Competency Test (optional)**  
* Install rust, compile `bdk-ffi` and build and test `bdk-swift` or `bdk-kotlin`. 
* Read through the BDK docs.
* Use `bdk-cli` to walk through the ["Spending Policy Demo"]
* Install and run example `bdk-kotlin` or `bdk-swift` example wallet.
* Familiarity with basic rust, should be able to write basic structs and functions.

["Spending Policy Demo"]: https://bitcoindevkit.org/blog/2021/02/spending-policy-demo/

**Comment by dhruv-1001** [comment]
This issue was closed with PR #154, and released in v0.9.0. @notmandatory @thunderbiscuit

**Comment by thunderbiscuit** [comment]
This issue might need an update, as I think the Policy module in bdk will be replaced by the policy module in miniscript.

**Comment by LLFourn** [comment]
I would not implement `policy.rs` api because of this change FWIW.

**Comment by thunderbiscuit** [comment]
This feature was requested and added in the 1.0 release by #612.
