### ISSUE TITLE
Flutter packaging support for iOS and Android

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk-ffi#85]

**Comment by artfuldev** [comment]
Relevant links:
https://flutter.dev/docs/development/platform-integration/platform-channels
https://docs.flutter.dev/development/packages-and-plugins/developing-packages
https://medium.com/flutter/how-to-write-a-flutter-web-plugin-5e26c689ea1
https://github.com/flutter/plugins/tree/master/packages/url_launcher

**Comment by artfuldev** [comment]
We're probably gonna have to write a little bit of glue code (on both the platform side (for both android and ios) and flutter/dart side) to make this work. But until we have another way this is going to be our first approach.

**Comment by artfuldev** [comment]
The glue code is quite a bit of work. We're gonna let the community deal with this for the short term. Maybe when we have really polished swift and android packages we can revisit this decision.

**Comment by notmandatory** [comment]
@i5hi want to make sure you saw this, we are going to focus on getting the FFI APIs worked out instead of supporting Flutter.  Hopefully only having to add method channels for the apis you need will still easier for your project than doing all the FFI work also. Happy to discuss if you have other suggestions.

**Comment by i5hi** [comment]
Hey @notmandatory . Sorry for the really delayed responsed. Been relocating over the past few weeks.

We have halted this project for sometime to figure out how to handle descriptor backups before supporting more complex scripts. 

Makes sense for your guys to keep your work more general and not focus on flutter for now.

Will keep you posted on how things progress regarding the backup issue.
