### ISSUE TITLE
Add api to generate child keys from master key

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk-ffi#87]
**Description**

Add an API to `bdk-ffi` to derive a child key pair from a master extended key and a derivation path string (eg. "m/84'/1'/0'/0" or "m/84h/1h/0h/0").  Also test the new `bdk-ffi` functions and structs via the `bdk-kotlin` and/or `bdk-swift` projects. See the `bdk-cli` key -> [derive](https://github.com/bitcoindevkit/bdk-cli/blob/b0c78e0aef181b2156c29549c3e27712166a4e49/src/lib.rs#L1122) subcommand as an example.

**Expected Outcomes**  
* Update `bdk.udl` and `lib.rs` with functions and structs as needed
* Update `bdk-kotlin` or `bdk-swift` and add tests to cover new key generation functionality 

**Resources**
* [BDK Website](https://bitcoindevkit.org)
* [BDK github repo](https://github.com/bitcoindevkit/bdk)
* [BDK Discord](https://discord.gg/dstn4dQ)
* [uniffi-rs](https://mozilla.github.io/uniffi-rs/)

**Skills Required**  
* Experience with git. [Guide](https://git-scm.com/book/en/v2)
* Basic familiarity with rust. [First seven chapters of the book](https://doc.rust-lang.org/book/)
* Basic familiarity with Kotlin or Swift
* Familiarity with bitcoin descriptors and address generation

**Mentor(s)**  

@artfuldev @notmandatory 

**Difficulty**  

Medium

**Competency Test (optional)**  
* Install rust, compile `bdk-ffi` and build and test `bdk-swift` or `bdk-kotlin`. 
* Read through the BDK docs.
* Install and run example `bdk-kotlin` or `bdk-swift` example wallet.
* Familiarity with basic rust, should be able to write basic structs and functions.

**Comment by notmandatory** [comment]
@dhruv-1001 will be working on this issue this year's summer of bitcoin program.

**Comment by kirillzh** [comment]
@notmandatory, @dhruv-1001, @artfuldev, what are your thoughts on providing full descriptor extended key with the master derivation path and master fingerprint in addition to the `xpub`, as opposed to just the `xpub`? As far as I can tell, current WIP implementation in #154 only provides the `xpub` key, in a format like: `xpub123` but not the full descriptor extended key, in a format like: `[asdfgast/84'/1'/0'/0']xpub/*`. These pieces of information [seem to be important](https://github.com/bitcoin/bitcoin/blob/master/doc/descriptors.md#key-origin-identification) when working with hardware wallets and signing PSBTs:
> In order to describe scripts whose signing keys reside on another device, it may be necessary to identify the master key and derivation path an xpub was derived with.
> 
> For example, when following BIP44, it would be useful to describe a change chain directly as xpub.../44'/0'/0'/1/* where xpub... corresponds with the master key m. Unfortunately, since there are hardened derivation steps that follow the xpub, this descriptor does not let you compute scripts without access to the corresponding private keys. Instead, it should be written as xpub.../1/*, where xpub corresponds to m/44'/0'/0'.
>
> When interacting with a hardware device, it may be necessary to include the entire path from the master down. [BIP174](https://github.com/bitcoin/bips/blob/master/bip-0174.mediawiki) standardizes this by providing the master key fingerprint (first 32 bit of the Hash160 of the master pubkey), plus all derivation steps. To support constructing these, we permit providing this key origin information inside the descriptor language, even though it does not affect the actual scriptPubKeys it refers to.

**Comment by notmandatory** [comment]
@kirillzh that is a good idea to include the key origin with the derived key. I'll work with @dhruv-1001 and see if we can get it into #154.

**Comment by dhruv-1001** [comment]
This issue can be closed, as it was implemented through PR #154, and released in v0.9.0 
@notmandatory @thunderbiscuit
