### ISSUE TITLE
Add github actions CI pipeline

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk-ffi#88]
Create github actions CI build and test pipline that must pass before a PR can be merged.

Must have:

1. Check format and clippy and build rust project for MSRV (TBD) and latest stable

**Comment by fireballpoint1** [comment]
Hi @notmandatory I am looking to start contributing. Do you think this would be a nice first issue to start with ? I am new to rust but have good experience with CI/CD pipelines on azure (it is very similar to github)

**Comment by thunderbiscuit** [comment]
I think the scope of this is now reduced quite a bit, which should help you @fireballpoint1. All 3 language bindings projects have been moved to their own repositories, so the only thing it should have is step 1 in the list above. @notmandatory what do you think?

**Comment by fireballpoint1** [comment]
@thunderbiscuit Would it be possible to point me to some documentation on how we check format and clippy (if we do use it right now) ? 
I'll start working on a branch on my fork and raise a PR.

**Comment by notmandatory** [comment]
Hi @fireballpoint1 you can take a look at how the ` bdk` CI job works, the one for this project will be easier because there aren't any features to test separately, see here: https://github.com/notmandatory/bdk/blob/0efbece41a482be6b6de55f7348aedf4588ccae5/.github/workflows/cont_integration.yml#L7-L59

Also you can read up on how Github actions work here: https://docs.github.com/en/actions

**Comment by notmandatory** [comment]
@fireballpoint1 are you still working on this? If not I'm going to work on a PR for it next week.

**Comment by fireballpoint1** [comment]
@notmandatory You can go ahead and work on this. I am contributing to another org as a part of SoB. Won't be abe to do this in parallel.

**Comment by notmandatory** [comment]
I took out the parts about testing with bdk-kotlin and bdk-swift. This will need to be done in separate PRs in those repos.
