### ISSUE TITLE
Current build of native library breaks version on Maven Central

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoindevkit/bdk-ffi#91]
Because of the new API (`txid`). This threw me in for a loop today but it finally clicked. The error I was getting was just so completely unrelated that it took me a while to figure it out.

So for now if you're pulling the library from Maven Central (`0.1.2`), you need to build the native lib on a detached head state at commit e2269f759a16db388e87fc9f589bca0cc9d050d3.

**Comment by thunderbiscuit** [comment]
Low cost solution to this right now (until we can ship the fat jars or whatever comes with the native libs embedded) would be to create a tag for each Maven Central release, and just let people know in the readme. "Whatever version is in your dependencies you should pull that tag and build the native library version for that particular release" type of thing.

**Comment by notmandatory** [comment]
The .jar and .aar on maven central should already include the required rust binaries. Maybe you need to clear your build env? 

Anyway you're right that I should have tagged the commit I used to create the build for the maven central release, it is b390a95ae, I pushed one now called v0.1.2.

**Comment by notmandatory** [comment]
We can certainly make the rust libs smaller by building them in release mode.  And we have issue #76 to include libs for more target. I'd like to be able to include at least the linux x86_64, darwin x86_64 and aarch64, and win x86 targets in our .jar builds. If the release builds are small enough we could include others, next on my list would be linux aarch64 (used on some small single board computers).

**Comment by thunderbiscuit** [comment]
Mind if I make a PR for this? I think what happened with 0.1.2 is probably that it was built on a Linux machine, and the way we have it setup in the `build.sh` file, it only adds the library on your development machine. Shouldn't be too hard to ensure we build and add a few architectures, no matter the building machine.

**Comment by thunderbiscuit** [comment]
I think this is really more a discussion for #76. Closing now.
