### ISSUE TITLE
Can `bdk::template::Bip84` be used in Kotlin ?

### ISSUE THREAD

**Issue by w0xlt** [bitcoindevkit/bdk-ffi#98]
In Rust, the following command can be used to build a descriptor.

```rust
Bip84(xpriv.clone(), KeychainKind::External),
```

Is this struct (`Bip84`) available in Kotlin ?

**Comment by notmandatory** [comment]
We don't currently have bdk templates available in the language bindings (Kotlin, Swift, Python) but I'll leave this here as a place holder issue for adding it.

**Comment by thunderbiscuit** [comment]
We'll be keeping track of bip-compliant templates in #165.
